### ISSUE TITLE
Login on staging requires 2 attempts

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#426]
Since we updated our SAML login this week, staging is now requiring you to login twice.  The first time you are redirected back to the login page, and the second time you login it works.

@sfrunza13 wonders on Slack if it's related to changes we made to cookies/session.

**Comment by sfrunza13** [comment]
The session cookie is set as a result of a request initiated by microsoft, the "partition key" for the __session cookie in prod is "https://senecacollege.ca", in dev we do not have this problem because the partition key for the cookie is "htttp://localhost". For now changing __session back to lax should probably fix this.
