### ISSUE TITLE
Bug: landing page not fully responsive

### ISSUE THREAD

**Issue by humphd** [DevelopingSpace/starchart#496]
The landing page needs a few fixes to be more responsive.

First, we need to make the `<Flex>` use `flexWrap` so it will wrap the cards.  Here it is now wide and narrow (should wrap in narrow):

<img width="1152" alt="Screenshot 2023-04-01 at 6 33 27 PM" src="https://user-images.githubusercontent.com/427398/229318832-ef4eed9a-3c39-440e-a771-5f834144c925.png">

<img width="495" alt="Screenshot 2023-04-01 at 6 33 36 PM" src="https://user-images.githubusercontent.com/427398/229318838-76ef5b79-fde6-4aef-8e3b-7da3fb9c8d37.png">

Second, if I do add `flexWrap='wrap'` there is some odd sizing issues with the cards and text:

<img width="746" alt="Screenshot 2023-04-01 at 6 34 05 PM" src="https://user-images.githubusercontent.com/427398/229318841-05c49a1c-921f-4714-b7bf-cc27c2de860a.png">

cc @Eakam1007, @Myrfion, @Ririio

**Comment by Ririio** [comment]
![image](https://user-images.githubusercontent.com/32577022/229325395-f440c1b1-e768-478f-8c00-d10bfa66d9fc.png)

Is this a good enough width for a column based card?

**Comment by Ririio** [comment]
I was wondering if `flexDirection` would be better, because you can set when you want it to be a `column` or `row`?

**Comment by Eakam1007** [comment]
@humphd Seems like the height for these is fixed in some way. Do you want these to not expand to fill the screen between the narrow and wide viewpoints? So, something like this:
<img width="546" alt="image" src="https://user-images.githubusercontent.com/67077705/229569733-8c7a7ed8-7543-4f56-bb2e-1559b6ba07c1.png">

And for narrow:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/67077705/229569852-bdc298a5-00db-42ad-8faf-fdcd9ce01b2a.png">

**Comment by humphd** [comment]
Yeah, what you have is better.
