### ISSUE TITLE
Error for duplicating DNS records doesn't have a proper error message.

### ISSUE THREAD

**Issue by cychu42** [DevelopingSpace/starchart#505]
## Description

When I tried to create a DNS record with same name, type, and value on staging, it would give me this error message page:
![image](https://user-images.githubusercontent.com/83015577/229532791-758cf4ab-d822-419b-a159-72b0f21195ab.png)
While it does prevent users from duplicating DNS records, I imagine the message is not very helpful for users, so some text should be there to explain what's wrong.

## Recreating the bug
On staging, create 2 DNS records with the same name, type, and value.

**Comment by cychu42** [comment]
Some update:
After talking to Denes, it seems it shouldn't even throw error when creating duplicates of same name+type+value.
Also, the error screen is currently without the text:
![image](https://user-images.githubusercontent.com/83015577/229833414-88a75c38-5a74-4f77-9707-4c641fc35417.png)

**Comment by humphd** [comment]
STR:

- create an A Record with name `test` and value `192.158.2.1`
- create a second A Record with name `test` and value `192.158.2.1`
- notice the `Application Error`

Discussion from meeting today: we should rename `doesDnsRecordExist` to `isDuplicateCname`, and change the logic so that it only errors if the record is a `CNAME` with a value that already exists (i.e., we'd allow duplicates of other types of records):

https://github.com/DevelopingSpace/starchart/blob/main/app/models/dns-record.server.ts#L111-L132

**Comment by humphd** [comment]
I think it should be OK, since our PK is an incrementing integer.  If it's going to break something, I'm also OK with not allowing it. We're not building DNS for an advanced user, only for students who can't manage it on their own.

**Comment by cychu42** [comment]
Yeah, I don't think it would break the database.
