### ISSUE TITLE
Add a lib That Handles DNS Modules

### ISSUE THREAD

**Issue by Genne23v** [DevelopingSpace/starchart#8]
Add a lib file for other modules to manipulate  DNS records in `Route 53`

- Configurability of AWS Route 53 SDK so that it can be used in multiple environments
- Ability to create, update, delete DNS records in hosted zone
- Capability to determine whether DNS records have been propagated
- Expire a domain after certain period of time is passed from creation
- Email notification before domain expiration 
- Filter inappropriate domain name 
- Unit tests for the module
- Add a mock environment for tests

**Comment by humphd** [comment]
I'm excited to see this getting started!  Some initial thoughts.

We can likely break this up into a few pieces, and I suspect @dadolhay will have thoughts about the API as well, since he needs it for the certificate flow.

To begin (0.1/0.2), I wonder if we should focus on doing something really simple, and limit ourselves to the following:

- Configurability of AWS Route 53 SDK so that it can be used in multiple environments
- Ability to create, update, delete DNS records in hosted zone
- Unit tests for the module
- Add a mock environment for tests

With Remix, this probably should live in `app/lib/dns.server.ts` (i.e., note the [`.server.ts` extension](https://remix.run/docs/en/v1/pages/gotchas#server-code-in-client-bundles)), since we'll only call it from server-side code.

A possible (initial) API might look like this (we can add more in later releases):

```ts
// We only support a subset of DNS resource record types
enum RecordType {
  A = "A",
  AAAA = "AAAA",
  CNAME = "CNAME",
  TXT = "TXT",
}

export { RecordType }

export const createRecord = (type: RecordType, name: string, value: string): Promise<void> => {}
export const getRecord = (type: RecordType, name: string): Promise<string> => {}
export const updateRecord = (type: RecordType, name: string, value: string): Promise<void> => {}
export const deleteRecord = (type: RecordType, name: string, value: string): Promise<void> => {}
```

All config (i.e., region, credentials, hosted zone) should get picked-up on startup via environment variables (i.e., we don't need to pass any of that into the calls above).

We should be able to write Jest unit tests for this and have it work against mocks or a [Dockerized moto server](http://docs.getmoto.org/en/latest/docs/server_mode.html#run-using-docker).

Those are just some quick thoughts.  None of this is set in stone.

**Comment by Genne23v** [comment]
Yes, actually I wanted to talk about reducing the scope of this issue on Wed. I didn't think filtering words, expire domain matters at the beginning. Thank you for the feedback. I will write another issue for split work.

**Comment by humphd** [comment]
I think you can keep this one as a meta issue, and file a bunch of smaller ones that link back here, if you want.

**Comment by humphd** [comment]
Doing some other work today, I stumbled on these docs for what is an isn't allowed in record names: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DomainNameFormat.html

**Comment by humphd** [comment]
@Genne23v can we close this now, and do remaining work in follow ups?

**Comment by Genne23v** [comment]
Yes, We can close this issue. I think remaining issues are being followed up with other tickets.
